---

- name: Install base packages
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
      - locales
      - build-essential
      - acl
      - ntp
      - htop
      - git
      - supervisor
      - python3-pip
  tags:
    - packages
    - packages.security

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
    - skip_ansible_lint
  